edition = "2024"
match_block_trailing_comma = true
newline_style = "Unix"
use_field_init_shorthand = true
fn_params_layout = "Vertical"
match_arm_leading_pipes = "Preserve"
use_small_heuristics = "Off"
use_try_shorthand = true
