[package]
name = "cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
publish.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
composer.workspace = true
clients.workspace = true
builder.workspace = true
clap.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "ansi"] }

[lints]
workspace = true
