[package]
name = "composer"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
publish.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]

[lints]
workspace = true
