[package]
name = "clients"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
publish.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
digest.workspace = true
hex.workspace = true
reqwest = { version = "0.13.2", default-features = false, features = ["json", "rustls", "query"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url = "2"

[dev-dependencies]
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter", "chrono"] }
tokio = { workspace = true, features = ["full"] }
tracing-tree = "0.3"

[lints]
workspace = true
